[package]
name = "klandestin"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.15.0", features = ["full", "macros"] }
tokio = { version = "1.44.2", features = ["tracing", "macros", "rt-multi-thread", "signal", "process"] }
